### ISSUE TITLE
I am getting this issue trying to boot to usb device

### ISSUE THREAD

**Issue by RickyHunter024** [raspberryenvoie/odysseyn1x#18] opened 2020-12-11 09:46 UTC
![image](https://user-images.githubusercontent.com/38816578/101888157-75174000-3ba6-11eb-881b-e05126b593c9.jpeg)

**Comment by raspberryenvoie** [comment] 2020-12-11 11:16
Are you still able to boot?

**Comment by RickyHunter024** [comment] 2020-12-11 11:19
I waited like 20/30 minutes and it's stuck at this so I just force shut down

**Comment by raspberryenvoie** [comment] 2020-12-11 11:50
#6

**Comment by RickyHunter024** [comment] 2020-12-11 11:51
It worked now I had to install the iso file again because it was corrupted

**Comment by raspberryenvoie** [comment] 2020-12-11 11:51
So you're getting the same problem as #6. Try updating your Bios if it isn't up to date.

**Comment by raspberryenvoie** [comment] 2020-12-11 11:52
Great! So I'm closing this issue

**Comment by RickyHunter024** [comment] 2020-12-11 11:53
Sry for wasting your time

**Closed as completed by raspberryenvoie** 2020-12-11 11:52 UTC
Labels: bug

**Comment by RickyHunter024** [comment] 2020-12-11 11:53
Just another question is there an option to ssh?

**Comment by raspberryenvoie** [comment] 2020-12-11 11:58
You can do it yourself throught command line select shell, run iproxy then run ssh. I'll add an option in a future release

**Comment by RickyHunter024** [comment] 2020-12-11 12:07
Ok thanks!!

**Comment by raspberryenvoie** [comment] 2020-12-11 12:16
np

**Comment by ghost** [comment] 2020-12-12 06:17
I thought it would be helpful to mention that the ACPI errors are usually nothing to worry about. :)

**Comment by raspberryenvoie** [comment] 2020-12-12 18:44
I believe those errors are from caused by the manufacturer's badly implemented BIOS.

**Comment by raspberryenvoie** [comment] 2021-01-03 13:53
> Just another question is there an option to ssh?

[v2.9](https://github.com/raspberryenvoie/odysseyn1x/releases/tag/v2.9) adds an option to do that.
